Repository retest/recheck-web, pull requests merged in 2020-03, with the labels that each got.

#536 Update extensions
  pom.xml
Labels: cla-signed

#535 Fix/update recheck
  pom.xml
  src/test/java/de/retest/web/it/RecheckRemoteWebElementFailingIT.java
  src/test/java/de/retest/web/it/RootElementPeerNullIT.java
  src/test/java/de/retest/web/it/SimplePageDiffIT.java
Labels: cla-signed

#528 Fix test for compatibility with mockito 3.3.0
  src/test/java/de/retest/web/selenium/css/HasTest.java
Labels: cla-signed

#538 Enable screenshots for example report test
  src/test/java/de/retest/web/it/WikipediaIT.java
Labels: cla-signed

#540 Fix viewport only
  CHANGELOG.md
  src/main/java/de/retest/web/RecheckWebProperties.java
  src/main/java/de/retest/web/screenshot/ScreenshotProviders.java
Labels: cla-signed

#539 Improve RecheckWebOptions
  CHANGELOG.md
  src/main/java/de/retest/web/RecheckWebOptions.java
  src/main/java/de/retest/web/RecheckWebProperties.java
  src/main/java/de/retest/web/screenshot/ScreenshotProviders.java
  src/main/java/de/retest/web/screenshot/ViewportOnlyMinimalScreenshot.java
  src/main/java/de/retest/web/screenshot/ViewportOnlyScreenshot.java
Labels: cla-signed

#541 Bump recheck version to 1.10.0
  pom.xml
Labels: cla-signed

#542 Bump extensions
  pom.xml
Labels: cla-signed

#544 Finalize changelog for release
  CHANGELOG.md
Labels: cla-signed

#545 Release/v1.10.0
  CHANGELOG.md
  pom.xml
  src/main/java/de/retest/web/DefaultWebValueFinder.java
  src/main/java/de/retest/web/RecheckWebOptions.java
  src/main/java/de/retest/web/RecheckWebProperties.java
  src/main/java/de/retest/web/screenshot/ScreenshotProviders.java
  src/main/java/de/retest/web/screenshot/ViewportOnlyMinimalScreenshot.java
  src/main/java/de/retest/web/screenshot/ViewportOnlyScreenshot.java
  src/test/java/de/retest/web/RecheckSeleniumAdapterIT.java
  src/test/java/de/retest/web/it/RecheckRemoteWebElementFailingIT.java
  src/test/java/de/retest/web/it/RootElementPeerNullIT.java
  src/test/java/de/retest/web/it/SimplePageDiffIT.java
  src/test/java/de/retest/web/it/WikipediaIT.java
Labels: cla-signed

#546 Fix missing coverage for SonarCloud
  ci/script.sh
  pom.xml
Labels: cla-signed

#543 Feature/naming strategy bugfixes
  CHANGELOG.md
  src/main/java/de/retest/web/selenium/ActionbasedCheckNamingStrategy.java
  src/test/java/de/retest/web/selenium/ActionbasedCheckNamingStrategyTest.java
Labels: cla-signed

#548 Feature/fix changelog
  CHANGELOG.md
Labels: cla-signed

#549 Revert "Fix visibility"
  CHANGELOG.md
  src/main/java/de/retest/web/RecheckWebOptions.java
Labels: bug, cla-signed

#550 Prepare changelog for release
  CHANGELOG.md
Labels: cla-signed

#551 Hotfix/v1.10.1
  CHANGELOG.md
  src/main/java/de/retest/web/RecheckWebOptions.java
Labels: cla-signed

#552 Add mergify configuration
  .mergify.yml
Labels: cla-signed

#553 Convert line separators to unix style
  src/main/java/de/retest/web/selenium/css/DefaultSelectors.java
  src/main/java/de/retest/web/selenium/css/Has.java
  src/main/java/de/retest/web/selenium/css/PredicateBuilder.java
  src/main/java/de/retest/web/selenium/css/RegexTransformer.java
  src/main/java/de/retest/web/selenium/css/Selector.java
  src/main/java/de/retest/web/selenium/css/Transformer.java
  src/test/java/de/retest/web/it/TestHealerCssSelectorIT.java
  src/test/java/de/retest/web/selenium/css/HasTest.java
  src/test/java/de/retest/web/selenium/css/PredicateBuilderTest.java
  src/test/java/de/retest/web/selenium/css/RegexTransformerTest.java
  src/test/resources/de/retest/web/it/TestHealerCssSelectorIT-changed.html
  src/test/resources/de/retest/web/it/TestHealerCssSelectorIT.html
  src/test/resources/pages/frame-diff.html
  src/test/resources/pages/frame-outer.html
  src/test/resources/pages/frame-page.html
  src/test/resources/pages/frame.html
  src/test/resources/pages/showcase/assets/default.css
  src/test/resources/pages/showcase/assets/init.js
  src/test/resources/pages/showcase/assets/layout.css
  src/test/resources/pages/showcase/assets/media-queries.css
  src/test/resources/retest/recheck/de.retest.web.it.TestHealerCssSelectorIT/setup.00.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.TestHealerCssSelectorIT/setup.01.recheck/retest.xml
Labels: cla-signed

#554 Bump recheck version to 1.10.1-beta.1
  pom.xml
Labels: cla-signed, dependencies

#555 Add a gitattributes file, covering this repository's file types
  .gitattributes
Labels: cla-signed

#556 Bump recheck version to 1.10.1
  pom.xml
Labels: cla-signed, dependencies

#557 Fix typos in README file
  README.md
Labels: cla-signed

#559 Prepare changelog for 1.10.2
  CHANGELOG.md
Labels: cla-signed

#560 Hotfix/v1.10.2
  CHANGELOG.md
  pom.xml
Labels: cla-signed

#558 Add skipCheck() method to our drivers
  CHANGELOG.md
  src/main/java/de/retest/web/selenium/UnbreakableDriver.java
Labels: cla-signed

#561 Feature/unify tab index
  CHANGELOG.md
  src/main/resources/defaults.yaml
  src/main/resources/javascript/getAllElementsByPath.js
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-FirefoxDriver.open.recheck/retest.xml
Labels: cla-signed

#566 Bump recheck version to 1.10.2-beta.1
  pom.xml
Labels: cla-signed, dependencies

#567 Bump recheck version to 1.10.2
  pom.xml
Labels: cla-signed, dependencies

#568 Prepare changelog for release 1.10.3
  CHANGELOG.md
Labels: cla-signed

#569 Hotfix/v1.10.3
  CHANGELOG.md
  pom.xml
Labels: cla-signed

#562 Feature/check clickability
  src/main/resources/javascript/getAllElementsByPath.js
  src/test/java/de/retest/web/it/IsCoveredIT.java
  src/test/java/de/retest/web/it/SimplePageDiffIT.java
  src/test/java/de/retest/web/testutils/PageFactory.java
  src/test/resources/pages/covered-page.html
  src/test/resources/retest/recheck/de.retest.web.it.CenterIT/center-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.CenterIT/center-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/empty-article-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/empty-article-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/simple-webelement-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/simple-webelement-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.00.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.01.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.02.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.03.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.04.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.05.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimplePageDiffIT/testSimpleChange.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimplePageIT/simple-page-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimplePageIT/simple-page-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleRecheckShowcaseIT/simpleShowcase.index.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-ChromeDriver.click.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-FirefoxDriver.click.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SpecialContainerIT/special-container-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.TestHealerCssSelectorIT/setup.00.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.TestHealerCssSelectorIT/setup.01.recheck/retest.xml
Labels: cla-signed
