Repository retest/recheck-web, pull requests merged in 2020-01, with the labels that each got.

#479 Fix/ie compatibility
  CHANGELOG.md
  src/main/resources/javascript/getAllElementsByPath.js
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.02.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.03.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.04.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.05.recheck/retest.xml
Labels: cla-signed

#474 Feature/fix cascading frames
  .retest/recheck.ignore
  CHANGELOG.md
  src/main/java/de/retest/web/FrameConverter.java
  src/test/java/de/retest/web/it/FramePageIT.java
  src/test/java/de/retest/web/testutils/PageFactory.java
  src/test/resources/pages/frame-diff.html
  src/test/resources/pages/frame-outer.html
  src/test/resources/pages/frame-page.html
  src/test/resources/pages/frame.html
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-ChromeDriver.open.recheck/screenshot/html.png
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-FirefoxDriver.open.recheck/screenshot/html.png
Labels: cla-signed

#473 Feature/omit screenshots
  .retest/retest.properties
  src/main/java/de/retest/web/screenshot/ScreenshotProviders.java
Labels: cla-signed

#480 Feature/multi frame problem
  src/test/resources/pages/frame-outer.html
  src/test/resources/pages/frame-page.html
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.FramePageIT/frame-page-FirefoxDriver.open.recheck/retest.xml
Labels: cla-signed

#481 Feature/ret 1917 implement warning creation
  CHANGELOG.md
  src/main/java/de/retest/web/RecheckSeleniumAdapter.java
  src/main/java/de/retest/web/selenium/QualifiedElementWarning.java
  src/main/java/de/retest/web/selenium/TestHealer.java
  src/main/java/de/retest/web/selenium/UnbreakableDriver.java
  src/main/java/de/retest/web/selenium/WriteToResultWarningConsumer.java
  src/test/java/de/retest/web/RecheckSeleniumAdapterIT.java
  src/test/java/de/retest/web/RecheckSeleniumAdapterTest.java
  src/test/java/de/retest/web/selenium/TestHealerTest.java
  src/test/java/de/retest/web/selenium/WriteToResultWarningConsumerTest.java
  src/test/resources/de/retest/web/AutoHealingTest.html
  src/test/resources/retest/recheck/de.retest.web.RecheckSeleniumAdapterIT/warnings_should_be_notified_properly_on_breaking_change.a.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.RecheckSeleniumAdapterIT/warnings_should_be_notified_properly_on_breaking_change.b.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.RecheckSeleniumAdapterIT/warnings_should_be_notified_properly_on_breaking_change.open.recheck/retest.xml
Labels: cla-signed, enhancement

#482 Update geckodriver to latest version (v0.26.0)
  ci/before.sh
Labels: cla-signed

#483 Move travis from EOL trusty to current LTS (bionic)
  .retest/recheck.ignore
  .travis.yml
  src/test/java/de/retest/web/it/SimplePageDiffIT.testSimpleChange.approved.txt
  src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.FormPageIT/form-page-ChromeDriver.open.recheck/screenshot/html_2313683bacb030fc125f7c8729309d368e3600a93d90ef31556579d1750ba7f8.png
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/html-element-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/html-element-ChromeDriver.open.recheck/screenshot/html_b0398bd8a34b4b9128404e8c7b6ecb99d35238103cddf4bd8bb30363dbca8c84.png
  src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.ShowcaseIT/showcase-ChromeDriver.open.recheck/screenshot/html.png
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.00.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.00.recheck/screenshot/html_9e89a28664cb34cbc114361ba379150ae88479b261987b04a56ed2d6e5332785.png
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.01.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.01.recheck/screenshot/html_c86c3e033fa787a176bf39972d4a3b6a47671667d54d8ff36d3e4c6c92e4a1b8.png
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.02.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.02.recheck/screenshot/html_d6adf2ea133f217ecd49419a365389d3cb3245396717468fe4ad9a94400e201b.png
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.03.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.03.recheck/screenshot/html_59e039f18a11f10078aaac8cde2e7425e05c76537b9f8e7107470b4bf9c02735.png
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.04.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.04.recheck/screenshot/html_36ce6fdeb63ae205e5ac0dcd087114e71231f5d0de0b0ae4def0e66846be247f.png
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.05.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.05.recheck/screenshot/html_36ce6fdeb63ae205e5ac0dcd087114e71231f5d0de0b0ae4def0e66846be247f.png
  src/test/resources/retest/recheck/de.retest.web.it.SimpleRecheckShowcaseIT/simpleShowcase.index.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleRecheckShowcaseIT/simpleShowcase.index.recheck/screenshot/html.png
Labels: cla-signed

#484 Squash tests into single test to avoid relying on side effects
  src/test/java/de/retest/web/it/RecheckRemoteWebElementIT.java
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-ChromeDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-FirefoxDriver.open.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.RecheckRemoteWebElementIT/findElement-equals-driver-FirefoxDriver.open.recheck/screenshot/html_55bf18063eed7a040d95559c1a8689df5118c2d589738e9d491872f3b9153f2d.png
Labels: cla-signed

#488 Fix test
  src/test/java/de/retest/web/it/SimplePageDiffIT.testSimpleChange.approved.txt
Labels: cla-signed

#485 Changed wording in logging from "Found 0 frame(s)" to "Found 0 sub-frame(s)"
  src/main/java/de/retest/web/FrameConverter.java
Labels: cla-signed

#490 Missing word in README, minor wording nitpick
  README.md
Labels: cla-signed

#491 Update recheck to intermediate version to find errors early
  pom.xml
  src/main/java/de/retest/web/selenium/By.java
Labels: cla-signed

#492 Allow to locally enable/disable screenshots, e.g. for GM creation
  CHANGELOG.md
  src/main/java/de/retest/web/RecheckWebOptions.java
  src/main/java/de/retest/web/screenshot/ScreenshotProviders.java
Labels: cla-signed

#494 Add recheck to the ignored updates
  .dependabot/config.yml
Labels: cla-signed, dependencies

#495 Add Clemens to Dependabot reviewers
  .dependabot/config.yml
Labels: cla-signed

#496 Finalize changelog for release 1.8.1
  CHANGELOG.md
Labels: cla-signed

#497 Hotfix/v1.8.1
  CHANGELOG.md
  src/main/resources/javascript/getAllElementsByPath.js
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.02.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.03.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.04.recheck/retest.xml
  src/test/resources/retest/recheck/de.retest.web.it.SimpleAutocheckingDriverShowcaseIT/index.05.recheck/retest.xml
Labels: cla-signed

#499 Bump recheck version to 1.9.0-beta.1
  pom.xml
Labels: cla-signed

#500 Bump recheck version to 1.9.0-beta.1
  pom.xml
Labels: cla-signed

#501 Revert "Bump recheck version to 1.9.0-beta.1"
  pom.xml
Labels: cla-signed

#503 Ensure compatibility with GnuPG 2
  ci/before_deploy.sh
Labels: cla-signed

#504 Ensure compatibility with GnuPG 2
  pom.xml
Labels: cla-signed

#502 Rename variable to parent, because this is what it is semantically
  src/main/resources/javascript/getAllElementsByPath.js
Labels: cla-signed

#505 Bump extensions
  pom.xml
Labels: cla-signed

#506 Bump recheck version to 1.9.0-beta.2
  pom.xml
Labels: cla-signed

#508 Bumb recheck version to 1.9.0
  pom.xml
Labels: cla-signed

#509 Bump extensions
  pom.xml
Labels: cla-signed

#510 Finalize changelog for release 1.9.0
  CHANGELOG.md
Labels: cla-signed

#513 Ignore all recheck deps
  .dependabot/config.yml
Labels: cla-signed

#514 Release/v1.9.0
  CHANGELOG.md
  ci/before_deploy.sh
  pom.xml
Labels: cla-signed
